### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by behdad** [googlei18n/cu2qu#24]
```
======================================================================
FAIL: test_results_unchanged (cu2qu.test.cu2qu_test.CurveToQuadraticTest)
Tests that the results of conversion haven't changed since the time
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/behdad/SSD/distillery/cu2qu/Lib/cu2qu/test/cu2qu_test.py", line 74, in test_results_unchanged
    self.assertEqual(results, expected)
AssertionError: defaultdict(<type 'int'>, {2: 1, 3: 6, 4: 17, 5: 88, 6: 244, 7: 412, 8: 231, 9: 1}) != {3: 5, 4: 31, 5: 74, 6: 228, 7: 416, 8: 242, 9: 4}

======================================================================
FAIL: test_results_unchanged_multiple (cu2qu.test.cu2qu_test.CurveToQuadraticTest)
Test that conversion results are unchanged for multiple curves.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/behdad/SSD/distillery/cu2qu/Lib/cu2qu/test/cu2qu_test.py", line 93, in test_results_unchanged_multiple
    self.assertEqual(results, expected)
AssertionError: defaultdict(<type 'int'>, {8: 51, 6: 5, 7: 44}) != {8: 62, 9: 1, 6: 3, 7: 34}

----------------------------------------------------------------------
```

**Comment by behdad** [comment]
Hah.  I get different numbers every time I run the tests!

**Comment by behdad** [comment]
Oh, because I'm running tests using "python setup.py test", which does not invoke the random-seed code.
